import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F8FAFC" },
  scrollArea: { flex: 1, backgroundColor: "#F8FAFC" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
  },
  loadingInner: { alignItems: "center" },
  loadingSpinnerWrap: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#CCFBF1",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  loadingTitle: { fontSize: 16, fontWeight: "600", color: "#0F172A" },
  loadingSubtitle: { fontSize: 14, color: "#64748B", marginTop: 4 },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 24,
  },
  errorIconWrap: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
  },
  errorTitle: { fontSize: 24, fontWeight: "700", color: "#0F172A", marginBottom: 12 },
  errorMessage: {
    fontSize: 16,
    color: "#475569",
    textAlign: "center",
    marginBottom: 32,
    paddingHorizontal: 16,
    lineHeight: 22,
  },
  errorActions: { flexDirection: "row", gap: 12 },
  rowCenterPX2: { flexDirection: "row", alignItems: "center", paddingHorizontal: 8 },
  btnOutlineText: { color: "#334155", fontWeight: "600", marginLeft: 8 },
  btnPrimaryText: { color: "#FFFFFF", fontWeight: "600", marginLeft: 8 },
  headerWrap: { backgroundColor: "#FFFFFF", paddingHorizontal: 24, paddingBottom: 16, paddingTop: 12 },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E2E8F0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
  },
  backBtnText: { fontSize: 16, fontWeight: "600", marginLeft: 8, color: "#0F172A" },
  qrBtn: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 12,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  qrBtnText: { color: "#3B82F6", fontSize: 14, fontWeight: "700", marginLeft: 8 },
  headerTitleRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  headerTitleCol: { flex: 1, paddingRight: 16 },
  headerTitle: { fontSize: 28, fontWeight: "700", marginBottom: 12, lineHeight: 34, color: "#0F172A" },
  jobNumberPill: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#E0E7FF",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  jobNumberText: { fontSize: 14, fontWeight: "500", marginLeft: 6, color: "#3730A3" },
  statusBadge: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 12 },
  statusBadgeText: { fontSize: 12, fontWeight: "700", color: "#0F172A" },
  description: { fontSize: 14, lineHeight: 18, marginTop: 16, color: "#475569" },
  contentWrap: { paddingHorizontal: 24, paddingVertical: 24, gap: 20 },
  cardBase: {
    backgroundColor: "#FFFFFF",
    borderColor: "#E2E8F0",
    borderWidth: 1,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
    borderRadius: 12,
  },
  cardBody: { padding: 3 },
  rowBetween: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  rowCenterFlex1: { flexDirection: "row", alignItems: "center", flex: 1 },
  progressIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#3B82F6",
    alignItems: "center",
    justifyContent: "center",
  },
  progressTextWrap: { marginLeft: 16, flex: 1 },
  progressTitle: { fontSize: 18, fontWeight: "700", color: "#0F172A" },
  progressSubtitle: { fontSize: 14, color: "#64748B", marginTop: 4 },
  progressPercent: { fontSize: 28, fontWeight: "700", color: "#3B82F6", marginLeft: 8 },
  progressBarBg: { height: 12, backgroundColor: "#E2E8F0", borderRadius: 999, overflow: "hidden", marginTop: 12 },
  progressBarFill: { height: "100%", borderRadius: 999 },
  rowCenterMB4: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  siteIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  cardTitle: { fontSize: 18, fontWeight: "700", color: "#0F172A", marginLeft: 16 },
  infoBox: {
    backgroundColor: "#F8FAFC",
    borderRadius: 12,
    padding: 9,
    borderWidth: 1,
    borderColor: "#E2E8F0",
  },
  infoBoxTitle: { fontSize: 16, color: "#0F172A", fontWeight: "600", marginBottom: 8 },
  rowCenter: { flexDirection: "row", alignItems: "center" },
  infoBoxSubtitle: { fontSize: 14, color: "#475569", marginLeft: 8 },
  rowCenterMB5: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
  vGap3: { gap: 12 },
  rowBetweenMB2: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  metaRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 8 },
  chip: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#EEF2FF', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  chipText: { color: '#1E3A8A', fontSize: 12, fontWeight: '700', marginLeft: 6 },
  chipSuccess: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#ECFDF5', borderWidth: 1, borderColor: '#A7F3D0', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
  chipTextSuccess: { color: '#047857', fontSize: 12, fontWeight: '700', marginLeft: 6 },
  timelineIconSmall: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
  },
  timelineLabel: { fontSize: 14, fontWeight: "600", color: "#0F172A", marginLeft: 12 },
  timelineDate: { fontSize: 14, fontWeight: "700", color: "#0F172A" },
  timelineTime: { fontSize: 12, color: "#64748B", marginLeft: 52 },
  infoBoxSuccess: {
    backgroundColor: "#ECFDF5",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#A7F3D0",
  },
  timelineIconSmallSuccess: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
  },
  timelineDateSuccess: { fontSize: 14, fontWeight: "700", color: "#047857" },
  timelineTimeSuccess: { fontSize: 12, color: "#047857", marginLeft: 52 },
  startWrap: { marginBottom: 8, marginTop: 8, backgroundColor: "#3B82F6", borderColor: "#3B82F6", borderRadius: 12 },
  startBtn: {
    borderRadius: 12,
    padding: 16,
  },
  rowCenterJustifyCenter: { flexDirection: "row", alignItems: "center", justifyContent: "center" },
  startIconWrap: { borderRadius: 8, backgroundColor: "rgba(255,255,255,0.2)", alignItems: "center", justifyContent: "center" },
  startText: { color: "#FFFFFF", fontSize: 20, fontWeight: "700", marginLeft: 16 },
  mb2: { marginBottom: 8 },
  sectionTitle: { fontSize: 20, fontWeight: "700", color: "#0F172A", marginLeft: 16 },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  modalContentWrap: { width: '100%', maxWidth: 360, backgroundColor: '#FFFFFF', borderRadius: 16, padding: 20, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 20, elevation: 6 },
  qrHeader: { alignItems: 'center', marginBottom: 16 },
  qrTitle: { fontSize: 18, fontWeight: '700', color: '#0F172A' },
  qrSubtitle: { fontSize: 13, color: '#64748B', marginTop: 4, textAlign: 'center' },
  qrBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 12 },
  qrJobInfo: { marginTop: 12, alignItems: 'center' },
  qrJobTitle: { fontSize: 16, fontWeight: '700', color: '#0F172A', textAlign: 'center' },
  qrJobNumber: { fontSize: 13, color: '#475569', marginTop: 4 },
  qrCloseWrap: { marginTop: 16 },
  qrCloseBtn: { backgroundColor: '#3B82F6', borderRadius: 12, alignItems: 'center', paddingVertical: 12 },
  qrCloseText: { color: '#FFFFFF', fontSize: 16, fontWeight: '700' },
  qrActionsRow: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 16 },
  qrDownloadIconBtn: { width: 46, height: 46, borderRadius: 12, backgroundColor: '#111827', alignItems: 'center', justifyContent: 'center' },
  qrCloseBtnWide: { flex: 1 },
});