/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type IdNameDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type AssetDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  url: string;
};

export type ListManagerDto = {
  id: string;
  email: string;
  fullName: string;
  createdAt: string;
  createdBy: IdNameDto;
  image: AssetDto | null;
};

export type PaginationResponseDTO = {
  previousPage?: number | null;
  nextPage?: number | null;
  total: number;
  count: number;
};

export type ListManagerResponseDto = {
  message: string;
  data: ListManagerDto[];
  pagination: PaginationResponseDTO;
};

export type ListGeneralDto = {
  id: string;
  email: string;
  fullName: string;
  createdAt: string;
  image: AssetDto | null;
};

export type ListGeneralResponseDto = {
  message: string;
  data: ListGeneralDto[];
  pagination: PaginationResponseDTO;
};

export type CreateManagerDto = {
  email: string;
  /**
   * @format binary
   */
  photo?: Blob;
  fullName: string;
  customerId: string;
};

export type IdDto = {
  /**
   * @format uuid
   */
  id: string;
};

export type MessageResponseWithIdDataDto = {
  message: string;
  data: IdDto;
};

export type UpdateManagerDto = {
  fullName?: string;
  /**
   * @format binary
   */
  photo?: Blob;
};

export type CreateGeneralDto = {
  email: string;
  /**
   * @format binary
   */
  photo?: Blob;
  fullName: string;
};

export type UpdateGeneralDto = {
  fullName?: string;
  email?: string;
  /**
   * @format binary
   */
  photo?: Blob;
};

export type GetMeDto = {
  id: string;
  fullName: string;
  email: string;
  image: AssetDto | null;
};

export type GetMeResponseDto = {
  message: string;
  data: GetMeDto;
};

export type LoginUserRequestDto = {
  email: string;
};

export type MessageResponseDto = {
  message: string;
};

export type VerrifyOtpDto = {
  otp: string;
  email: string;
};

export type LoginUserUserDto = {
  /**
   * @format uuid
   */
  id: string;
  fullName: string;
  email: string;
};

export type LoginUserDto = {
  token: string;
  user: LoginUserUserDto;
};

export type LoginUserResponseDto = {
  message: string;
  data: LoginUserDto;
};

export type LoginManagerManagerDto = {
  /**
   * @format uuid
   */
  id: string;
  fullName: string;
  email: string;
  /**
   * @format uuid
   */
  customerId: string;
};

export type LoginManagerDto = {
  token: string;
  user: LoginManagerManagerDto;
};

export type LoginManagerResponseDto = {
  message: string;
  data: LoginManagerDto;
};

export type ListSOWDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  group: IdNameDto | null;
};

export type ListSOWResponseDto = {
  message: string;
  data: ListSOWDto[];
  pagination: PaginationResponseDTO;
};

export type GetSOWResponseDto = {
  message: string;
  data: ListSOWDto;
};

export type CreateScopeOfWorkRequestDto = {
  /**
   * @format uuid
   */
  sowGroupId?: string;
  title: string;
  description: string;
};

export type UpdateScopeOfWorkRequestDto = {
  /**
   * @format uuid
   */
  sowGroupId?: string;
  title?: string;
  description?: string;
};

export type ListSOWGroupDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
};

export type ListSOWGroupResponseDto = {
  message: string;
  data: ListSOWGroupDto[];
  pagination: PaginationResponseDTO;
};

export type GetSOWGroupSow = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
};

export type GetSOWGroupDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  sows: GetSOWGroupSow[];
};

export type GetSOWGroupResponseDto = {
  message: string;
  data: GetSOWGroupDto;
};

export type CreateScopeOfWorkGroupRequestDto = {
  description?: string;
  title: string;
};

export type UpdateSowGroupRequestDto = {
  description?: string;
  title?: string;
};

export type ListSiteLocationDto = {
  /**
   * @format uuid
   */
  id: string;
  lineOne: string;
  city: string;
  state: string;
};

export type ListSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: ListSiteLocationDto;
  customer: IdNameDto;
  createdBy: IdNameDto | null;
};

export type ListSiteResponseDto = {
  message: string;
  data: ListSiteDto[];
  pagination: PaginationResponseDTO;
};

export type GetSiteLocationDto = {
  placeId?: string;
  lineTwo?: string | null;
  /**
   * @format uuid
   */
  id: string;
  lineOne: string;
  city: string;
  state: string;
  postcode: string;
  latitude: number;
  longitude: number;
};

export type GetSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: GetSiteLocationDto;
  customer: IdNameDto;
  createdBy: IdNameDto | null;
};

export type GetSiteResponseDto = {
  message: string;
  data: GetSiteDto;
};

export type CreateSiteLocationDto = {
  placeId?: string;
  lineTwo?: string;
  lineOne: string;
  city: string;
  state: string;
  postcode: string;
  latitude: number;
  longitude: number;
};

export type CreateSiteRequestDto = {
  description?: string;
  title: string;
  /**
   * @format uuid
   */
  customerId: string;
  location: CreateSiteLocationDto;
};

export type UpdateSiteLocationDto = {
  placeId?: string;
  lineTwo?: string;
  lineOne?: string;
  city?: string;
  state?: string;
  postcode?: string;
  latitude?: number;
  longitude?: number;
};

export type UpdateSiteRequestDto = {
  title?: string;
  description?: string;
  location?: UpdateSiteLocationDto;
};

export type GetJobSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  address: string;
  city: string;
};

export type ListJobDto = {
  status: "scheduled" | "In Progress" | "Completed" | "Cancelled";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  description: string | null;
  jobNumber: number;
  startAt: string | null;
  createdAt: string;
  site?: GetJobSiteDto | null;
};

export type ListJobResponseDto = {
  message: string;
  data: ListJobDto[];
  pagination: PaginationResponseDTO;
};

export type GetJobChecklistDto = {
  status: "Pending" | "Ongoing" | "Completed" | "Cancelled";
  /**
   * @format uuid
   */
  id: string;
  name: string;
  remarks: string | null;
  attachments: AssetDto[];
};

export type GetJobDto = {
  status: "scheduled" | "In Progress" | "Completed" | "Cancelled";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  description: string | null;
  jobNumber: number;
  startAt: string | null;
  createdAt: string;
  site?: GetJobSiteDto | null;
  checklists: GetJobChecklistDto[];
};

export type GetJobResponseDto = {
  message: string;
  data: GetJobDto;
};

export type CreateJobChecklistDto = {
  remarks?: string;
  /**
   * @format uuid
   */
  sowId: string;
};

export type CreateJobRequestDto = {
  title: string;
  description?: string;
  siteId: string;
  /**
   * @format date-time
   */
  startAt: string;
  checklists: CreateJobChecklistDto[];
  /**
   * @format uuid
   */
  customerId: string;
};

export type UpdateChecklistSowRequestDto = {
  status?: "Pending" | "Ongoing" | "Completed" | "Cancelled";
  /**
   * @format binary
   */
  attachments?: Blob;
  /**
   * @format uuid
   */
  id: string;
};

export type StartJobRequestDto = {
  /**
   * @format uuid
   */
  jobId: string;
  latitude: number;
  longitude: number;
  /**
   * @format date-time
   */
  startedAt: string;
};

export type ListCustomerDto = {
  email?: string | null;
  id: string;
  name: string;
  createdBy: IdNameDto;
};

export type ListCustomerResponseDto = {
  message: string;
  data: ListCustomerDto[];
  pagination: PaginationResponseDTO;
};

export type CreateCustomerRequestDto = {
  name: string;
  email?: string;
};

export type GetCustomerSiteDto = {
  address: string;
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type GetCustomerDto = {
  email?: string | null;
  id: string;
  name: string;
  createdBy: IdNameDto;
  sites: GetCustomerSiteDto[];
};

export type GetCustomerResponseDto = {
  message: string;
  data: GetCustomerDto;
};

export type UpdateCustomerRequestDto = {
  name?: string;
  email?: string;
};
