/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
import * as reactQuery from "@tanstack/react-query";
import {
  type QueriesContext,
  useQueriesContext,
  queryKeyFn,
} from "./queriesContext";
import { deepMerge } from "./queriesUtils";
import type * as Fetcher from "./queriesFetcher";
import { queriesFetch } from "./queriesFetcher";
import type * as Schemas from "./queriesSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type UserControllerGetManagersQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
  /**
   * @format uuid
   */
  customerId?: string;
};

export type UserControllerGetManagersError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerGetManagersVariables = {
  queryParams?: UserControllerGetManagersQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerGetManagers = (
  variables: UserControllerGetManagersVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListManagerResponseDto,
    UserControllerGetManagersError,
    undefined,
    {},
    UserControllerGetManagersQueryParams,
    {}
  >({ url: "/user/managers", method: "get", ...variables, signal });

export function userControllerGetManagersQuery(
  variables: UserControllerGetManagersVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListManagerResponseDto>;
};

export function userControllerGetManagersQuery(
  variables: UserControllerGetManagersVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListManagerResponseDto>)
    | reactQuery.SkipToken;
};

export function userControllerGetManagersQuery(
  variables: UserControllerGetManagersVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/user/managers",
      operationId: "userControllerGetManagers",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchUserControllerGetManagers(variables, signal),
  };
}

export const useSuspenseUserControllerGetManagers = <
  TData = Schemas.ListManagerResponseDto,
>(
  variables: UserControllerGetManagersVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListManagerResponseDto,
      UserControllerGetManagersError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListManagerResponseDto,
    UserControllerGetManagersError,
    TData
  >({
    ...userControllerGetManagersQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useUserControllerGetManagers = <
  TData = Schemas.ListManagerResponseDto,
>(
  variables: UserControllerGetManagersVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListManagerResponseDto,
      UserControllerGetManagersError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListManagerResponseDto,
    UserControllerGetManagersError,
    TData
  >({
    ...userControllerGetManagersQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type UserControllerGetGeneralsQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
  /**
   * @format uuid
   */
  customerId?: string;
};

export type UserControllerGetGeneralsError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerGetGeneralsVariables = {
  queryParams?: UserControllerGetGeneralsQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerGetGenerals = (
  variables: UserControllerGetGeneralsVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListGeneralResponseDto,
    UserControllerGetGeneralsError,
    undefined,
    {},
    UserControllerGetGeneralsQueryParams,
    {}
  >({ url: "/user/general", method: "get", ...variables, signal });

export function userControllerGetGeneralsQuery(
  variables: UserControllerGetGeneralsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListGeneralResponseDto>;
};

export function userControllerGetGeneralsQuery(
  variables: UserControllerGetGeneralsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListGeneralResponseDto>)
    | reactQuery.SkipToken;
};

export function userControllerGetGeneralsQuery(
  variables: UserControllerGetGeneralsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/user/general",
      operationId: "userControllerGetGenerals",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchUserControllerGetGenerals(variables, signal),
  };
}

export const useSuspenseUserControllerGetGenerals = <
  TData = Schemas.ListGeneralResponseDto,
>(
  variables: UserControllerGetGeneralsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListGeneralResponseDto,
      UserControllerGetGeneralsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListGeneralResponseDto,
    UserControllerGetGeneralsError,
    TData
  >({
    ...userControllerGetGeneralsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useUserControllerGetGenerals = <
  TData = Schemas.ListGeneralResponseDto,
>(
  variables: UserControllerGetGeneralsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListGeneralResponseDto,
      UserControllerGetGeneralsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListGeneralResponseDto,
    UserControllerGetGeneralsError,
    TData
  >({
    ...userControllerGetGeneralsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type UserControllerCreateManagerError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerCreateManagerVariables = {
  body: Schemas.CreateManagerDto;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerCreateManager = (
  variables: UserControllerCreateManagerVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerCreateManagerError,
    Schemas.CreateManagerDto,
    {},
    {},
    {}
  >({ url: "/user/createManager", method: "post", ...variables, signal });

export const useUserControllerCreateManager = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      UserControllerCreateManagerError,
      UserControllerCreateManagerVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerCreateManagerError,
    UserControllerCreateManagerVariables
  >({
    mutationFn: (variables: UserControllerCreateManagerVariables) =>
      fetchUserControllerCreateManager(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UserControllerUpdateManagerPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type UserControllerUpdateManagerError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerUpdateManagerVariables = {
  body?: Schemas.UpdateManagerDto;
  pathParams: UserControllerUpdateManagerPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerUpdateManager = (
  variables: UserControllerUpdateManagerVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerUpdateManagerError,
    Schemas.UpdateManagerDto,
    {},
    {},
    UserControllerUpdateManagerPathParams
  >({ url: "/user/manager/{id}", method: "patch", ...variables, signal });

export const useUserControllerUpdateManager = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      UserControllerUpdateManagerError,
      UserControllerUpdateManagerVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerUpdateManagerError,
    UserControllerUpdateManagerVariables
  >({
    mutationFn: (variables: UserControllerUpdateManagerVariables) =>
      fetchUserControllerUpdateManager(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UserControllerCreateGeneralError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerCreateGeneralVariables = {
  body: Schemas.CreateGeneralDto;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerCreateGeneral = (
  variables: UserControllerCreateGeneralVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerCreateGeneralError,
    Schemas.CreateGeneralDto,
    {},
    {},
    {}
  >({ url: "/user/createGeneral", method: "post", ...variables, signal });

export const useUserControllerCreateGeneral = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      UserControllerCreateGeneralError,
      UserControllerCreateGeneralVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerCreateGeneralError,
    UserControllerCreateGeneralVariables
  >({
    mutationFn: (variables: UserControllerCreateGeneralVariables) =>
      fetchUserControllerCreateGeneral(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UserControllerUpdateGeneralPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type UserControllerUpdateGeneralError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerUpdateGeneralVariables = {
  body?: Schemas.UpdateGeneralDto;
  pathParams: UserControllerUpdateGeneralPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerUpdateGeneral = (
  variables: UserControllerUpdateGeneralVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerUpdateGeneralError,
    Schemas.UpdateGeneralDto,
    {},
    {},
    UserControllerUpdateGeneralPathParams
  >({ url: "/user/general/{id}", method: "patch", ...variables, signal });

export const useUserControllerUpdateGeneral = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      UserControllerUpdateGeneralError,
      UserControllerUpdateGeneralVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerUpdateGeneralError,
    UserControllerUpdateGeneralVariables
  >({
    mutationFn: (variables: UserControllerUpdateGeneralVariables) =>
      fetchUserControllerUpdateGeneral(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type UserControllerDeleteUserPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type UserControllerDeleteUserError = Fetcher.ErrorWrapper<undefined>;

export type UserControllerDeleteUserVariables = {
  pathParams: UserControllerDeleteUserPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchUserControllerDeleteUser = (
  variables: UserControllerDeleteUserVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerDeleteUserError,
    undefined,
    {},
    {},
    UserControllerDeleteUserPathParams
  >({ url: "/user/{id}", method: "delete", ...variables, signal });

export const useUserControllerDeleteUser = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      UserControllerDeleteUserError,
      UserControllerDeleteUserVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    UserControllerDeleteUserError,
    UserControllerDeleteUserVariables
  >({
    mutationFn: (variables: UserControllerDeleteUserVariables) =>
      fetchUserControllerDeleteUser(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerGetMeUserError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerGetMeUserVariables = QueriesContext["fetcherOptions"];

export const fetchAuthControllerGetMeUser = (
  variables: AuthControllerGetMeUserVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeUserError,
    undefined,
    {},
    {},
    {}
  >({ url: "/auth/user/me", method: "get", ...variables, signal });

export function authControllerGetMeUserQuery(
  variables: AuthControllerGetMeUserVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetMeResponseDto>;
};

export function authControllerGetMeUserQuery(
  variables: AuthControllerGetMeUserVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetMeResponseDto>)
    | reactQuery.SkipToken;
};

export function authControllerGetMeUserQuery(
  variables: AuthControllerGetMeUserVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/auth/user/me",
      operationId: "authControllerGetMeUser",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAuthControllerGetMeUser(variables, signal),
  };
}

export const useSuspenseAuthControllerGetMeUser = <
  TData = Schemas.GetMeResponseDto,
>(
  variables: AuthControllerGetMeUserVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetMeResponseDto,
      AuthControllerGetMeUserError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeUserError,
    TData
  >({
    ...authControllerGetMeUserQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAuthControllerGetMeUser = <TData = Schemas.GetMeResponseDto,>(
  variables: AuthControllerGetMeUserVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetMeResponseDto,
      AuthControllerGetMeUserError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeUserError,
    TData
  >({
    ...authControllerGetMeUserQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AuthControllerGetMeCustomerError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerGetMeCustomerVariables =
  QueriesContext["fetcherOptions"];

export const fetchAuthControllerGetMeCustomer = (
  variables: AuthControllerGetMeCustomerVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeCustomerError,
    undefined,
    {},
    {},
    {}
  >({ url: "/auth/customer/me", method: "get", ...variables, signal });

export function authControllerGetMeCustomerQuery(
  variables: AuthControllerGetMeCustomerVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetMeResponseDto>;
};

export function authControllerGetMeCustomerQuery(
  variables: AuthControllerGetMeCustomerVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetMeResponseDto>)
    | reactQuery.SkipToken;
};

export function authControllerGetMeCustomerQuery(
  variables: AuthControllerGetMeCustomerVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/auth/customer/me",
      operationId: "authControllerGetMeCustomer",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchAuthControllerGetMeCustomer(variables, signal),
  };
}

export const useSuspenseAuthControllerGetMeCustomer = <
  TData = Schemas.GetMeResponseDto,
>(
  variables: AuthControllerGetMeCustomerVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetMeResponseDto,
      AuthControllerGetMeCustomerError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeCustomerError,
    TData
  >({
    ...authControllerGetMeCustomerQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useAuthControllerGetMeCustomer = <
  TData = Schemas.GetMeResponseDto,
>(
  variables: AuthControllerGetMeCustomerVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetMeResponseDto,
      AuthControllerGetMeCustomerError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetMeResponseDto,
    AuthControllerGetMeCustomerError,
    TData
  >({
    ...authControllerGetMeCustomerQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type AuthControllerAdminLoginError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerAdminLoginVariables = {
  body: Schemas.LoginUserRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchAuthControllerAdminLogin = (
  variables: AuthControllerAdminLoginVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseDto,
    AuthControllerAdminLoginError,
    Schemas.LoginUserRequestDto,
    {},
    {},
    {}
  >({ url: "/auth/login/admin", method: "post", ...variables, signal });

export const useAuthControllerAdminLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseDto,
      AuthControllerAdminLoginError,
      AuthControllerAdminLoginVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseDto,
    AuthControllerAdminLoginError,
    AuthControllerAdminLoginVariables
  >({
    mutationFn: (variables: AuthControllerAdminLoginVariables) =>
      fetchAuthControllerAdminLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerStaffLoginError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerStaffLoginVariables = {
  body: Schemas.LoginUserRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchAuthControllerStaffLogin = (
  variables: AuthControllerStaffLoginVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseDto,
    AuthControllerStaffLoginError,
    Schemas.LoginUserRequestDto,
    {},
    {},
    {}
  >({ url: "/auth/login/staff", method: "post", ...variables, signal });

export const useAuthControllerStaffLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseDto,
      AuthControllerStaffLoginError,
      AuthControllerStaffLoginVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseDto,
    AuthControllerStaffLoginError,
    AuthControllerStaffLoginVariables
  >({
    mutationFn: (variables: AuthControllerStaffLoginVariables) =>
      fetchAuthControllerStaffLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerManagerLoginError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerManagerLoginVariables = {
  body: Schemas.LoginUserRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchAuthControllerManagerLogin = (
  variables: AuthControllerManagerLoginVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseDto,
    AuthControllerManagerLoginError,
    Schemas.LoginUserRequestDto,
    {},
    {},
    {}
  >({ url: "/auth/login/manager", method: "post", ...variables, signal });

export const useAuthControllerManagerLogin = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseDto,
      AuthControllerManagerLoginError,
      AuthControllerManagerLoginVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseDto,
    AuthControllerManagerLoginError,
    AuthControllerManagerLoginVariables
  >({
    mutationFn: (variables: AuthControllerManagerLoginVariables) =>
      fetchAuthControllerManagerLogin(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerVerifyUserOtpError = Fetcher.ErrorWrapper<undefined>;

export type AuthControllerVerifyUserOtpVariables = {
  body: Schemas.VerrifyOtpDto;
} & QueriesContext["fetcherOptions"];

export const fetchAuthControllerVerifyUserOtp = (
  variables: AuthControllerVerifyUserOtpVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.LoginUserResponseDto,
    AuthControllerVerifyUserOtpError,
    Schemas.VerrifyOtpDto,
    {},
    {},
    {}
  >({ url: "/auth/verify-otp/user", method: "post", ...variables, signal });

export const useAuthControllerVerifyUserOtp = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.LoginUserResponseDto,
      AuthControllerVerifyUserOtpError,
      AuthControllerVerifyUserOtpVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.LoginUserResponseDto,
    AuthControllerVerifyUserOtpError,
    AuthControllerVerifyUserOtpVariables
  >({
    mutationFn: (variables: AuthControllerVerifyUserOtpVariables) =>
      fetchAuthControllerVerifyUserOtp(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type AuthControllerVerifyManagerOtpError =
  Fetcher.ErrorWrapper<undefined>;

export type AuthControllerVerifyManagerOtpVariables = {
  body: Schemas.VerrifyOtpDto;
} & QueriesContext["fetcherOptions"];

export const fetchAuthControllerVerifyManagerOtp = (
  variables: AuthControllerVerifyManagerOtpVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.LoginManagerResponseDto,
    AuthControllerVerifyManagerOtpError,
    Schemas.VerrifyOtpDto,
    {},
    {},
    {}
  >({ url: "/auth/verify-otp/manager", method: "post", ...variables, signal });

export const useAuthControllerVerifyManagerOtp = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.LoginManagerResponseDto,
      AuthControllerVerifyManagerOtpError,
      AuthControllerVerifyManagerOtpVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.LoginManagerResponseDto,
    AuthControllerVerifyManagerOtpError,
    AuthControllerVerifyManagerOtpVariables
  >({
    mutationFn: (variables: AuthControllerVerifyManagerOtpVariables) =>
      fetchAuthControllerVerifyManagerOtp(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SowControllerSowsQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
};

export type SowControllerSowsError = Fetcher.ErrorWrapper<undefined>;

export type SowControllerSowsVariables = {
  queryParams?: SowControllerSowsQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowControllerSows = (
  variables: SowControllerSowsVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListSOWResponseDto,
    SowControllerSowsError,
    undefined,
    {},
    SowControllerSowsQueryParams,
    {}
  >({ url: "/sow", method: "get", ...variables, signal });

export function sowControllerSowsQuery(variables: SowControllerSowsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListSOWResponseDto>;
};

export function sowControllerSowsQuery(
  variables: SowControllerSowsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListSOWResponseDto>)
    | reactQuery.SkipToken;
};

export function sowControllerSowsQuery(
  variables: SowControllerSowsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/sow",
      operationId: "sowControllerSows",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSowControllerSows(variables, signal),
  };
}

export const useSuspenseSowControllerSows = <
  TData = Schemas.ListSOWResponseDto,
>(
  variables: SowControllerSowsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSOWResponseDto,
      SowControllerSowsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListSOWResponseDto,
    SowControllerSowsError,
    TData
  >({
    ...sowControllerSowsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSowControllerSows = <TData = Schemas.ListSOWResponseDto,>(
  variables: SowControllerSowsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSOWResponseDto,
      SowControllerSowsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListSOWResponseDto,
    SowControllerSowsError,
    TData
  >({
    ...sowControllerSowsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SowControllerCreateError = Fetcher.ErrorWrapper<undefined>;

export type SowControllerCreateVariables = {
  body: Schemas.CreateScopeOfWorkRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchSowControllerCreate = (
  variables: SowControllerCreateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SowControllerCreateError,
    Schemas.CreateScopeOfWorkRequestDto,
    {},
    {},
    {}
  >({ url: "/sow", method: "post", ...variables, signal });

export const useSowControllerCreate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SowControllerCreateError,
      SowControllerCreateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SowControllerCreateError,
    SowControllerCreateVariables
  >({
    mutationFn: (variables: SowControllerCreateVariables) =>
      fetchSowControllerCreate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SowControllerSowPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type SowControllerSowError = Fetcher.ErrorWrapper<undefined>;

export type SowControllerSowVariables = {
  pathParams: SowControllerSowPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowControllerSow = (
  variables: SowControllerSowVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetSOWResponseDto,
    SowControllerSowError,
    undefined,
    {},
    {},
    SowControllerSowPathParams
  >({ url: "/sow/{id}", method: "get", ...variables, signal });

export function sowControllerSowQuery(variables: SowControllerSowVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetSOWResponseDto>;
};

export function sowControllerSowQuery(
  variables: SowControllerSowVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetSOWResponseDto>)
    | reactQuery.SkipToken;
};

export function sowControllerSowQuery(
  variables: SowControllerSowVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/sow/{id}",
      operationId: "sowControllerSow",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSowControllerSow(variables, signal),
  };
}

export const useSuspenseSowControllerSow = <TData = Schemas.GetSOWResponseDto,>(
  variables: SowControllerSowVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSOWResponseDto,
      SowControllerSowError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetSOWResponseDto,
    SowControllerSowError,
    TData
  >({
    ...sowControllerSowQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSowControllerSow = <TData = Schemas.GetSOWResponseDto,>(
  variables: SowControllerSowVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSOWResponseDto,
      SowControllerSowError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetSOWResponseDto,
    SowControllerSowError,
    TData
  >({
    ...sowControllerSowQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SowControllerUpdatePathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type SowControllerUpdateError = Fetcher.ErrorWrapper<undefined>;

export type SowControllerUpdateVariables = {
  body?: Schemas.UpdateScopeOfWorkRequestDto;
  pathParams: SowControllerUpdatePathParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowControllerUpdate = (
  variables: SowControllerUpdateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SowControllerUpdateError,
    Schemas.UpdateScopeOfWorkRequestDto,
    {},
    {},
    SowControllerUpdatePathParams
  >({ url: "/sow/{id}", method: "patch", ...variables, signal });

export const useSowControllerUpdate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SowControllerUpdateError,
      SowControllerUpdateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SowControllerUpdateError,
    SowControllerUpdateVariables
  >({
    mutationFn: (variables: SowControllerUpdateVariables) =>
      fetchSowControllerUpdate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SowGroupControllerSowsQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
};

export type SowGroupControllerSowsError = Fetcher.ErrorWrapper<undefined>;

export type SowGroupControllerSowsVariables = {
  queryParams?: SowGroupControllerSowsQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowGroupControllerSows = (
  variables: SowGroupControllerSowsVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListSOWGroupResponseDto,
    SowGroupControllerSowsError,
    undefined,
    {},
    SowGroupControllerSowsQueryParams,
    {}
  >({ url: "/sowGroup", method: "get", ...variables, signal });

export function sowGroupControllerSowsQuery(
  variables: SowGroupControllerSowsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions,
  ) => Promise<Schemas.ListSOWGroupResponseDto>;
};

export function sowGroupControllerSowsQuery(
  variables: SowGroupControllerSowsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListSOWGroupResponseDto>)
    | reactQuery.SkipToken;
};

export function sowGroupControllerSowsQuery(
  variables: SowGroupControllerSowsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/sowGroup",
      operationId: "sowGroupControllerSows",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSowGroupControllerSows(variables, signal),
  };
}

export const useSuspenseSowGroupControllerSows = <
  TData = Schemas.ListSOWGroupResponseDto,
>(
  variables: SowGroupControllerSowsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSOWGroupResponseDto,
      SowGroupControllerSowsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListSOWGroupResponseDto,
    SowGroupControllerSowsError,
    TData
  >({
    ...sowGroupControllerSowsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSowGroupControllerSows = <
  TData = Schemas.ListSOWGroupResponseDto,
>(
  variables: SowGroupControllerSowsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSOWGroupResponseDto,
      SowGroupControllerSowsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListSOWGroupResponseDto,
    SowGroupControllerSowsError,
    TData
  >({
    ...sowGroupControllerSowsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SowGroupControllerCreateError = Fetcher.ErrorWrapper<undefined>;

export type SowGroupControllerCreateVariables = {
  body: Schemas.CreateScopeOfWorkGroupRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchSowGroupControllerCreate = (
  variables: SowGroupControllerCreateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SowGroupControllerCreateError,
    Schemas.CreateScopeOfWorkGroupRequestDto,
    {},
    {},
    {}
  >({ url: "/sowGroup", method: "post", ...variables, signal });

export const useSowGroupControllerCreate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SowGroupControllerCreateError,
      SowGroupControllerCreateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SowGroupControllerCreateError,
    SowGroupControllerCreateVariables
  >({
    mutationFn: (variables: SowGroupControllerCreateVariables) =>
      fetchSowGroupControllerCreate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SowGroupControllerSowPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type SowGroupControllerSowError = Fetcher.ErrorWrapper<undefined>;

export type SowGroupControllerSowVariables = {
  pathParams: SowGroupControllerSowPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowGroupControllerSow = (
  variables: SowGroupControllerSowVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetSOWGroupResponseDto,
    SowGroupControllerSowError,
    undefined,
    {},
    {},
    SowGroupControllerSowPathParams
  >({ url: "/sowGroup/{id}", method: "get", ...variables, signal });

export function sowGroupControllerSowQuery(
  variables: SowGroupControllerSowVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetSOWGroupResponseDto>;
};

export function sowGroupControllerSowQuery(
  variables: SowGroupControllerSowVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetSOWGroupResponseDto>)
    | reactQuery.SkipToken;
};

export function sowGroupControllerSowQuery(
  variables: SowGroupControllerSowVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/sowGroup/{id}",
      operationId: "sowGroupControllerSow",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSowGroupControllerSow(variables, signal),
  };
}

export const useSuspenseSowGroupControllerSow = <
  TData = Schemas.GetSOWGroupResponseDto,
>(
  variables: SowGroupControllerSowVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSOWGroupResponseDto,
      SowGroupControllerSowError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetSOWGroupResponseDto,
    SowGroupControllerSowError,
    TData
  >({
    ...sowGroupControllerSowQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSowGroupControllerSow = <
  TData = Schemas.GetSOWGroupResponseDto,
>(
  variables: SowGroupControllerSowVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSOWGroupResponseDto,
      SowGroupControllerSowError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetSOWGroupResponseDto,
    SowGroupControllerSowError,
    TData
  >({
    ...sowGroupControllerSowQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SowGroupControllerUpdatePathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type SowGroupControllerUpdateError = Fetcher.ErrorWrapper<undefined>;

export type SowGroupControllerUpdateVariables = {
  body?: Schemas.UpdateSowGroupRequestDto;
  pathParams: SowGroupControllerUpdatePathParams;
} & QueriesContext["fetcherOptions"];

export const fetchSowGroupControllerUpdate = (
  variables: SowGroupControllerUpdateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SowGroupControllerUpdateError,
    Schemas.UpdateSowGroupRequestDto,
    {},
    {},
    SowGroupControllerUpdatePathParams
  >({ url: "/sowGroup/{id}", method: "patch", ...variables, signal });

export const useSowGroupControllerUpdate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SowGroupControllerUpdateError,
      SowGroupControllerUpdateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SowGroupControllerUpdateError,
    SowGroupControllerUpdateVariables
  >({
    mutationFn: (variables: SowGroupControllerUpdateVariables) =>
      fetchSowGroupControllerUpdate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SiteControllerSitesQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
  /**
   * @format uuid
   */
  customerId?: string;
};

export type SiteControllerSitesError = Fetcher.ErrorWrapper<undefined>;

export type SiteControllerSitesVariables = {
  queryParams?: SiteControllerSitesQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchSiteControllerSites = (
  variables: SiteControllerSitesVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListSiteResponseDto,
    SiteControllerSitesError,
    undefined,
    {},
    SiteControllerSitesQueryParams,
    {}
  >({ url: "/site", method: "get", ...variables, signal });

export function siteControllerSitesQuery(
  variables: SiteControllerSitesVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListSiteResponseDto>;
};

export function siteControllerSitesQuery(
  variables: SiteControllerSitesVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListSiteResponseDto>)
    | reactQuery.SkipToken;
};

export function siteControllerSitesQuery(
  variables: SiteControllerSitesVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/site",
      operationId: "siteControllerSites",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSiteControllerSites(variables, signal),
  };
}

export const useSuspenseSiteControllerSites = <
  TData = Schemas.ListSiteResponseDto,
>(
  variables: SiteControllerSitesVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSiteResponseDto,
      SiteControllerSitesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListSiteResponseDto,
    SiteControllerSitesError,
    TData
  >({
    ...siteControllerSitesQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSiteControllerSites = <TData = Schemas.ListSiteResponseDto,>(
  variables: SiteControllerSitesVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListSiteResponseDto,
      SiteControllerSitesError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListSiteResponseDto,
    SiteControllerSitesError,
    TData
  >({
    ...siteControllerSitesQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SiteControllerCreateError = Fetcher.ErrorWrapper<undefined>;

export type SiteControllerCreateVariables = {
  body: Schemas.CreateSiteRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchSiteControllerCreate = (
  variables: SiteControllerCreateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SiteControllerCreateError,
    Schemas.CreateSiteRequestDto,
    {},
    {},
    {}
  >({ url: "/site", method: "post", ...variables, signal });

export const useSiteControllerCreate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SiteControllerCreateError,
      SiteControllerCreateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SiteControllerCreateError,
    SiteControllerCreateVariables
  >({
    mutationFn: (variables: SiteControllerCreateVariables) =>
      fetchSiteControllerCreate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type SiteControllerSitePathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type SiteControllerSiteError = Fetcher.ErrorWrapper<undefined>;

export type SiteControllerSiteVariables = {
  pathParams: SiteControllerSitePathParams;
} & QueriesContext["fetcherOptions"];

export const fetchSiteControllerSite = (
  variables: SiteControllerSiteVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetSiteResponseDto,
    SiteControllerSiteError,
    undefined,
    {},
    {},
    SiteControllerSitePathParams
  >({ url: "/site/{id}", method: "get", ...variables, signal });

export function siteControllerSiteQuery(
  variables: SiteControllerSiteVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetSiteResponseDto>;
};

export function siteControllerSiteQuery(
  variables: SiteControllerSiteVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetSiteResponseDto>)
    | reactQuery.SkipToken;
};

export function siteControllerSiteQuery(
  variables: SiteControllerSiteVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/site/{id}",
      operationId: "siteControllerSite",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchSiteControllerSite(variables, signal),
  };
}

export const useSuspenseSiteControllerSite = <
  TData = Schemas.GetSiteResponseDto,
>(
  variables: SiteControllerSiteVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSiteResponseDto,
      SiteControllerSiteError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetSiteResponseDto,
    SiteControllerSiteError,
    TData
  >({
    ...siteControllerSiteQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useSiteControllerSite = <TData = Schemas.GetSiteResponseDto,>(
  variables: SiteControllerSiteVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetSiteResponseDto,
      SiteControllerSiteError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetSiteResponseDto,
    SiteControllerSiteError,
    TData
  >({
    ...siteControllerSiteQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type SiteControllerUpdateQueryParams = {
  id: string;
};

export type SiteControllerUpdateError = Fetcher.ErrorWrapper<undefined>;

export type SiteControllerUpdateVariables = {
  body?: Schemas.UpdateSiteRequestDto;
  queryParams: SiteControllerUpdateQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchSiteControllerUpdate = (
  variables: SiteControllerUpdateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    SiteControllerUpdateError,
    Schemas.UpdateSiteRequestDto,
    {},
    SiteControllerUpdateQueryParams,
    {}
  >({ url: "/site/{id}", method: "patch", ...variables, signal });

export const useSiteControllerUpdate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      SiteControllerUpdateError,
      SiteControllerUpdateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    SiteControllerUpdateError,
    SiteControllerUpdateVariables
  >({
    mutationFn: (variables: SiteControllerUpdateVariables) =>
      fetchSiteControllerUpdate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type JobControllerJobsQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
  /**
   * @format uuid
   */
  customerId?: string;
  /**
   * @format uuid
   */
  staffId?: string;
};

export type JobControllerJobsError = Fetcher.ErrorWrapper<undefined>;

export type JobControllerJobsVariables = {
  queryParams?: JobControllerJobsQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerJobs = (
  variables: JobControllerJobsVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListJobResponseDto,
    JobControllerJobsError,
    undefined,
    {},
    JobControllerJobsQueryParams,
    {}
  >({ url: "/job", method: "get", ...variables, signal });

export function jobControllerJobsQuery(variables: JobControllerJobsVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListJobResponseDto>;
};

export function jobControllerJobsQuery(
  variables: JobControllerJobsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListJobResponseDto>)
    | reactQuery.SkipToken;
};

export function jobControllerJobsQuery(
  variables: JobControllerJobsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/job",
      operationId: "jobControllerJobs",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchJobControllerJobs(variables, signal),
  };
}

export const useSuspenseJobControllerJobs = <
  TData = Schemas.ListJobResponseDto,
>(
  variables: JobControllerJobsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListJobResponseDto,
      JobControllerJobsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListJobResponseDto,
    JobControllerJobsError,
    TData
  >({
    ...jobControllerJobsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useJobControllerJobs = <TData = Schemas.ListJobResponseDto,>(
  variables: JobControllerJobsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListJobResponseDto,
      JobControllerJobsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListJobResponseDto,
    JobControllerJobsError,
    TData
  >({
    ...jobControllerJobsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type JobControllerCreateJobError = Fetcher.ErrorWrapper<undefined>;

export type JobControllerCreateJobVariables = {
  body: Schemas.CreateJobRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerCreateJob = (
  variables: JobControllerCreateJobVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerCreateJobError,
    Schemas.CreateJobRequestDto,
    {},
    {},
    {}
  >({ url: "/job", method: "post", ...variables, signal });

export const useJobControllerCreateJob = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      JobControllerCreateJobError,
      JobControllerCreateJobVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerCreateJobError,
    JobControllerCreateJobVariables
  >({
    mutationFn: (variables: JobControllerCreateJobVariables) =>
      fetchJobControllerCreateJob(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type JobControllerAssignStaffToJobPathParams = {
  /**
   * @format uuid
   */
  jobId: string;
  /**
   * @format uuid
   */
  staffId: string;
};

export type JobControllerAssignStaffToJobError =
  Fetcher.ErrorWrapper<undefined>;

export type JobControllerAssignStaffToJobVariables = {
  pathParams: JobControllerAssignStaffToJobPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerAssignStaffToJob = (
  variables: JobControllerAssignStaffToJobVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerAssignStaffToJobError,
    undefined,
    {},
    {},
    JobControllerAssignStaffToJobPathParams
  >({ url: "/job/{jobId}/{staffId}", method: "patch", ...variables, signal });

export const useJobControllerAssignStaffToJob = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      JobControllerAssignStaffToJobError,
      JobControllerAssignStaffToJobVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerAssignStaffToJobError,
    JobControllerAssignStaffToJobVariables
  >({
    mutationFn: (variables: JobControllerAssignStaffToJobVariables) =>
      fetchJobControllerAssignStaffToJob(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type JobControllerJobPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type JobControllerJobError = Fetcher.ErrorWrapper<undefined>;

export type JobControllerJobVariables = {
  pathParams: JobControllerJobPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerJob = (
  variables: JobControllerJobVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetJobResponseDto,
    JobControllerJobError,
    undefined,
    {},
    {},
    JobControllerJobPathParams
  >({ url: "/job/{id}", method: "get", ...variables, signal });

export function jobControllerJobQuery(variables: JobControllerJobVariables): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetJobResponseDto>;
};

export function jobControllerJobQuery(
  variables: JobControllerJobVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetJobResponseDto>)
    | reactQuery.SkipToken;
};

export function jobControllerJobQuery(
  variables: JobControllerJobVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/job/{id}",
      operationId: "jobControllerJob",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchJobControllerJob(variables, signal),
  };
}

export const useSuspenseJobControllerJob = <TData = Schemas.GetJobResponseDto,>(
  variables: JobControllerJobVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetJobResponseDto,
      JobControllerJobError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetJobResponseDto,
    JobControllerJobError,
    TData
  >({
    ...jobControllerJobQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useJobControllerJob = <TData = Schemas.GetJobResponseDto,>(
  variables: JobControllerJobVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetJobResponseDto,
      JobControllerJobError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetJobResponseDto,
    JobControllerJobError,
    TData
  >({
    ...jobControllerJobQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type JobControllerUpdateChecklistSowPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type JobControllerUpdateChecklistSowError =
  Fetcher.ErrorWrapper<undefined>;

export type JobControllerUpdateChecklistSowVariables = {
  body: Schemas.UpdateChecklistSowRequestDto;
  pathParams: JobControllerUpdateChecklistSowPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerUpdateChecklistSow = (
  variables: JobControllerUpdateChecklistSowVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerUpdateChecklistSowError,
    Schemas.UpdateChecklistSowRequestDto,
    {},
    {},
    JobControllerUpdateChecklistSowPathParams
  >({ url: "/job/checklistSow/{id}", method: "patch", ...variables, signal });

export const useJobControllerUpdateChecklistSow = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      JobControllerUpdateChecklistSowError,
      JobControllerUpdateChecklistSowVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerUpdateChecklistSowError,
    JobControllerUpdateChecklistSowVariables
  >({
    mutationFn: (variables: JobControllerUpdateChecklistSowVariables) =>
      fetchJobControllerUpdateChecklistSow(
        deepMerge(fetcherOptions, variables),
      ),
    ...options,
  });
};

export type JobControllerStartJobError = Fetcher.ErrorWrapper<undefined>;

export type JobControllerStartJobVariables = {
  body: Schemas.StartJobRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchJobControllerStartJob = (
  variables: JobControllerStartJobVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerStartJobError,
    Schemas.StartJobRequestDto,
    {},
    {},
    {}
  >({ url: "/job/start", method: "post", ...variables, signal });

export const useJobControllerStartJob = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      JobControllerStartJobError,
      JobControllerStartJobVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    JobControllerStartJobError,
    JobControllerStartJobVariables
  >({
    mutationFn: (variables: JobControllerStartJobVariables) =>
      fetchJobControllerStartJob(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type CustomerControllerCustomersQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
};

export type CustomerControllerCustomersError = Fetcher.ErrorWrapper<undefined>;

export type CustomerControllerCustomersVariables = {
  queryParams?: CustomerControllerCustomersQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerControllerCustomers = (
  variables: CustomerControllerCustomersVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListCustomerResponseDto,
    CustomerControllerCustomersError,
    undefined,
    {},
    CustomerControllerCustomersQueryParams,
    {}
  >({ url: "/customer", method: "get", ...variables, signal });

export function customerControllerCustomersQuery(
  variables: CustomerControllerCustomersVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions,
  ) => Promise<Schemas.ListCustomerResponseDto>;
};

export function customerControllerCustomersQuery(
  variables: CustomerControllerCustomersVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListCustomerResponseDto>)
    | reactQuery.SkipToken;
};

export function customerControllerCustomersQuery(
  variables: CustomerControllerCustomersVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/customer",
      operationId: "customerControllerCustomers",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchCustomerControllerCustomers(variables, signal),
  };
}

export const useSuspenseCustomerControllerCustomers = <
  TData = Schemas.ListCustomerResponseDto,
>(
  variables: CustomerControllerCustomersVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListCustomerResponseDto,
      CustomerControllerCustomersError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListCustomerResponseDto,
    CustomerControllerCustomersError,
    TData
  >({
    ...customerControllerCustomersQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useCustomerControllerCustomers = <
  TData = Schemas.ListCustomerResponseDto,
>(
  variables: CustomerControllerCustomersVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListCustomerResponseDto,
      CustomerControllerCustomersError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListCustomerResponseDto,
    CustomerControllerCustomersError,
    TData
  >({
    ...customerControllerCustomersQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CustomerControllerCreateError = Fetcher.ErrorWrapper<undefined>;

export type CustomerControllerCreateVariables = {
  body: Schemas.CreateCustomerRequestDto;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerControllerCreate = (
  variables: CustomerControllerCreateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    CustomerControllerCreateError,
    Schemas.CreateCustomerRequestDto,
    {},
    {},
    {}
  >({ url: "/customer", method: "post", ...variables, signal });

export const useCustomerControllerCreate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      CustomerControllerCreateError,
      CustomerControllerCreateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    CustomerControllerCreateError,
    CustomerControllerCreateVariables
  >({
    mutationFn: (variables: CustomerControllerCreateVariables) =>
      fetchCustomerControllerCreate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type CustomerControllerCustomerPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type CustomerControllerCustomerError = Fetcher.ErrorWrapper<undefined>;

export type CustomerControllerCustomerVariables = {
  pathParams: CustomerControllerCustomerPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerControllerCustomer = (
  variables: CustomerControllerCustomerVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetCustomerResponseDto,
    CustomerControllerCustomerError,
    undefined,
    {},
    {},
    CustomerControllerCustomerPathParams
  >({ url: "/customer/{id}", method: "get", ...variables, signal });

export function customerControllerCustomerQuery(
  variables: CustomerControllerCustomerVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetCustomerResponseDto>;
};

export function customerControllerCustomerQuery(
  variables: CustomerControllerCustomerVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetCustomerResponseDto>)
    | reactQuery.SkipToken;
};

export function customerControllerCustomerQuery(
  variables: CustomerControllerCustomerVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/customer/{id}",
      operationId: "customerControllerCustomer",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchCustomerControllerCustomer(variables, signal),
  };
}

export const useSuspenseCustomerControllerCustomer = <
  TData = Schemas.GetCustomerResponseDto,
>(
  variables: CustomerControllerCustomerVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetCustomerResponseDto,
      CustomerControllerCustomerError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetCustomerResponseDto,
    CustomerControllerCustomerError,
    TData
  >({
    ...customerControllerCustomerQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useCustomerControllerCustomer = <
  TData = Schemas.GetCustomerResponseDto,
>(
  variables: CustomerControllerCustomerVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetCustomerResponseDto,
      CustomerControllerCustomerError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetCustomerResponseDto,
    CustomerControllerCustomerError,
    TData
  >({
    ...customerControllerCustomerQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CustomerControllerUpdatePathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type CustomerControllerUpdateError = Fetcher.ErrorWrapper<undefined>;

export type CustomerControllerUpdateVariables = {
  body?: Schemas.UpdateCustomerRequestDto;
  pathParams: CustomerControllerUpdatePathParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerControllerUpdate = (
  variables: CustomerControllerUpdateVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseWithIdDataDto,
    CustomerControllerUpdateError,
    Schemas.UpdateCustomerRequestDto,
    {},
    {},
    CustomerControllerUpdatePathParams
  >({ url: "/customer/{id}", method: "patch", ...variables, signal });

export const useCustomerControllerUpdate = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseWithIdDataDto,
      CustomerControllerUpdateError,
      CustomerControllerUpdateVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseWithIdDataDto,
    CustomerControllerUpdateError,
    CustomerControllerUpdateVariables
  >({
    mutationFn: (variables: CustomerControllerUpdateVariables) =>
      fetchCustomerControllerUpdate(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type CustomerControllerDeletePathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type CustomerControllerDeleteError = Fetcher.ErrorWrapper<undefined>;

export type CustomerControllerDeleteVariables = {
  pathParams: CustomerControllerDeletePathParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerControllerDelete = (
  variables: CustomerControllerDeleteVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.MessageResponseDto,
    CustomerControllerDeleteError,
    undefined,
    {},
    {},
    CustomerControllerDeletePathParams
  >({ url: "/customer/{id}", method: "delete", ...variables, signal });

export const useCustomerControllerDelete = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      Schemas.MessageResponseDto,
      CustomerControllerDeleteError,
      CustomerControllerDeleteVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useQueriesContext();
  return reactQuery.useMutation<
    Schemas.MessageResponseDto,
    CustomerControllerDeleteError,
    CustomerControllerDeleteVariables
  >({
    mutationFn: (variables: CustomerControllerDeleteVariables) =>
      fetchCustomerControllerDelete(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type CustomerJobControllerJobsQueryParams = {
  /**
   * @minimum 0
   */
  take?: number;
  /**
   * @minimum 0
   */
  page?: number;
  search?: string;
  /**
   * @format uuid
   */
  staffId?: string;
  /**
   * @format uuid
   */
  customerId: string;
};

export type CustomerJobControllerJobsError = Fetcher.ErrorWrapper<undefined>;

export type CustomerJobControllerJobsVariables = {
  queryParams: CustomerJobControllerJobsQueryParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerJobControllerJobs = (
  variables: CustomerJobControllerJobsVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.ListJobResponseDto,
    CustomerJobControllerJobsError,
    undefined,
    {},
    CustomerJobControllerJobsQueryParams,
    {}
  >({ url: "/customers/job", method: "get", ...variables, signal });

export function customerJobControllerJobsQuery(
  variables: CustomerJobControllerJobsVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.ListJobResponseDto>;
};

export function customerJobControllerJobsQuery(
  variables: CustomerJobControllerJobsVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.ListJobResponseDto>)
    | reactQuery.SkipToken;
};

export function customerJobControllerJobsQuery(
  variables: CustomerJobControllerJobsVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/customers/job",
      operationId: "customerJobControllerJobs",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchCustomerJobControllerJobs(variables, signal),
  };
}

export const useSuspenseCustomerJobControllerJobs = <
  TData = Schemas.ListJobResponseDto,
>(
  variables: CustomerJobControllerJobsVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListJobResponseDto,
      CustomerJobControllerJobsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.ListJobResponseDto,
    CustomerJobControllerJobsError,
    TData
  >({
    ...customerJobControllerJobsQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useCustomerJobControllerJobs = <
  TData = Schemas.ListJobResponseDto,
>(
  variables: CustomerJobControllerJobsVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.ListJobResponseDto,
      CustomerJobControllerJobsError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.ListJobResponseDto,
    CustomerJobControllerJobsError,
    TData
  >({
    ...customerJobControllerJobsQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type CustomerJobControllerJobPathParams = {
  /**
   * @format uuid
   */
  id: string;
};

export type CustomerJobControllerJobError = Fetcher.ErrorWrapper<undefined>;

export type CustomerJobControllerJobVariables = {
  pathParams: CustomerJobControllerJobPathParams;
} & QueriesContext["fetcherOptions"];

export const fetchCustomerJobControllerJob = (
  variables: CustomerJobControllerJobVariables,
  signal?: AbortSignal,
) =>
  queriesFetch<
    Schemas.GetJobResponseDto,
    CustomerJobControllerJobError,
    undefined,
    {},
    {},
    CustomerJobControllerJobPathParams
  >({ url: "/customers/job/{id}", method: "get", ...variables, signal });

export function customerJobControllerJobQuery(
  variables: CustomerJobControllerJobVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (options: QueryFnOptions) => Promise<Schemas.GetJobResponseDto>;
};

export function customerJobControllerJobQuery(
  variables: CustomerJobControllerJobVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<Schemas.GetJobResponseDto>)
    | reactQuery.SkipToken;
};

export function customerJobControllerJobQuery(
  variables: CustomerJobControllerJobVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/customers/job/{id}",
      operationId: "customerJobControllerJob",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchCustomerJobControllerJob(variables, signal),
  };
}

export const useSuspenseCustomerJobControllerJob = <
  TData = Schemas.GetJobResponseDto,
>(
  variables: CustomerJobControllerJobVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetJobResponseDto,
      CustomerJobControllerJobError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useSuspenseQuery<
    Schemas.GetJobResponseDto,
    CustomerJobControllerJobError,
    TData
  >({
    ...customerJobControllerJobQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useCustomerJobControllerJob = <TData = Schemas.GetJobResponseDto,>(
  variables: CustomerJobControllerJobVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      Schemas.GetJobResponseDto,
      CustomerJobControllerJobError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useQueriesContext(options);
  return reactQuery.useQuery<
    Schemas.GetJobResponseDto,
    CustomerJobControllerJobError,
    TData
  >({
    ...customerJobControllerJobQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation =
  | {
      path: "/user/managers";
      operationId: "userControllerGetManagers";
      variables: UserControllerGetManagersVariables | reactQuery.SkipToken;
    }
  | {
      path: "/user/general";
      operationId: "userControllerGetGenerals";
      variables: UserControllerGetGeneralsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/auth/user/me";
      operationId: "authControllerGetMeUser";
      variables: AuthControllerGetMeUserVariables | reactQuery.SkipToken;
    }
  | {
      path: "/auth/customer/me";
      operationId: "authControllerGetMeCustomer";
      variables: AuthControllerGetMeCustomerVariables | reactQuery.SkipToken;
    }
  | {
      path: "/sow";
      operationId: "sowControllerSows";
      variables: SowControllerSowsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/sow/{id}";
      operationId: "sowControllerSow";
      variables: SowControllerSowVariables | reactQuery.SkipToken;
    }
  | {
      path: "/sowGroup";
      operationId: "sowGroupControllerSows";
      variables: SowGroupControllerSowsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/sowGroup/{id}";
      operationId: "sowGroupControllerSow";
      variables: SowGroupControllerSowVariables | reactQuery.SkipToken;
    }
  | {
      path: "/site";
      operationId: "siteControllerSites";
      variables: SiteControllerSitesVariables | reactQuery.SkipToken;
    }
  | {
      path: "/site/{id}";
      operationId: "siteControllerSite";
      variables: SiteControllerSiteVariables | reactQuery.SkipToken;
    }
  | {
      path: "/job";
      operationId: "jobControllerJobs";
      variables: JobControllerJobsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/job/{id}";
      operationId: "jobControllerJob";
      variables: JobControllerJobVariables | reactQuery.SkipToken;
    }
  | {
      path: "/customer";
      operationId: "customerControllerCustomers";
      variables: CustomerControllerCustomersVariables | reactQuery.SkipToken;
    }
  | {
      path: "/customer/{id}";
      operationId: "customerControllerCustomer";
      variables: CustomerControllerCustomerVariables | reactQuery.SkipToken;
    }
  | {
      path: "/customers/job";
      operationId: "customerJobControllerJobs";
      variables: CustomerJobControllerJobsVariables | reactQuery.SkipToken;
    }
  | {
      path: "/customers/job/{id}";
      operationId: "customerJobControllerJob";
      variables: CustomerJobControllerJobVariables | reactQuery.SkipToken;
    };
