/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type IdDto = {
  /**
   * @format uuid
   */
  id: string;
};

export type AssetDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  url: string;
};

export type GetMeDto = {
  role: "admin" | "cleaner" | "manager" | "customer manager";
  id: string;
  fullName: string;
  oneSignalId: string;
  email: string;
  cleaner: IdDto | null;
  manager: IdDto | null;
  customerUser: IdDto | null;
  image: AssetDto | null;
};

export type GetMeResponseDto = {
  message: string;
  data: GetMeDto;
};

export type LoginUserRequestDto = {
  email: string;
};

export type MessageResponseDto = {
  message: string;
};

export type VerrifyOtpDto = {
  otp: string;
  email: string;
};

export type LoginUserUserDto = {
  role: "admin" | "cleaner" | "manager" | "customer manager";
  /**
   * @format uuid
   */
  id: string;
  fullName: string;
  oneSignalId: string;
  email: string;
};

export type LoginUserDto = {
  token: string;
  user: LoginUserUserDto;
};

export type LoginUserResponseDto = {
  message: string;
  data: LoginUserDto;
};

export type IdNameDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type ListCustomerDto = {
  email?: string | null;
  id: string;
  name: string;
  createdBy: IdNameDto;
};

export type PaginationResponseDto = {
  previousPage?: number | null;
  nextPage?: number | null;
  total: number;
  count: number;
};

export type ListCustomerResponseDto = {
  message: string;
  data: ListCustomerDto[];
  pagination: PaginationResponseDto;
};

export type GetCustomerSummaryJobDataDto = {};

export type GetCustomerSummaryDto = {
  siteCount: number;
  usersCount: number;
  jobData: GetCustomerSummaryJobDataDto;
};

export type GetCustomerSummaryResponseDto = {
  message: string;
  data: GetCustomerSummaryDto;
};

export type ListCustomerInternalManagersDto = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format uuid
   */
  userId: string;
  name: string;
  email: string;
};

export type ListCustomerInternalManagersResponseDto = {
  message: string;
  data: ListCustomerInternalManagersDto[];
  pagination: PaginationResponseDto;
};

export type ListCustomerCustomerUserDto = {
  /**
   * @format uuid
   */
  id: string;
  /**
   * @format uuid
   */
  userId: string;
  name: string;
  email: string;
};

export type ListCustomerCustomerUserResponseDto = {
  message: string;
  data: ListCustomerCustomerUserDto[];
  pagination: PaginationResponseDto;
};

export type GetCustomerSiteDto = {
  address: string;
  /**
   * @format uuid
   */
  id: string;
  name: string;
};

export type GetCustomerDto = {
  email?: string | null;
  id: string;
  name: string;
  createdBy: IdNameDto;
  sites: GetCustomerSiteDto[];
};

export type GetCustomerResponseDto = {
  message: string;
  data: GetCustomerDto;
};

export type CreateCustomerRequestDto = {
  name: string;
  email?: string;
};

export type MessageResponseWithIdDataDto = {
  message: string;
  data: IdDto;
};

export type UpdateCustomerManagerDto = {
  added?: string[];
  removed?: string[];
};

export type UpdateCustomerRequestDto = {
  managers?: UpdateCustomerManagerDto;
  name?: string;
  email?: string;
};

export type JobByStatusDto = {
  status: "Scheduled" | "In Progress" | "Completed" | "Cancelled";
  count: number;
};

export type AdminDashboardCountSummaryDto = {
  totalClients: number;
  totalSites: number;
  totalCleaners: number;
  totalClientUsers: number;
  totalInternalManagers: number;
  jobByStatus: JobByStatusDto[];
};

export type AdminDashboardCountSummaryResponseDto = {
  message: string;
  data: AdminDashboardCountSummaryDto;
};

export type ListAdminStaffAttendanceDto = {
  /**
   * @format date-time
   */
  clockOut?: string | null;
  /**
   * @format uuid
   */
  id: string;
  site: IdNameDto;
  cleaner: IdNameDto;
  isOnline: boolean;
  /**
   * @format date-time
   */
  clockIn: string;
};

export type ListAdminStaffAttendanceResponseDto = {
  message: string;
  data: ListAdminStaffAttendanceDto[];
  pagination: PaginationResponseDto;
};

export type ListManagerUserDto = {
  id: string;
  email: string;
  fullName: string;
  /**
   * @format date-time
   */
  createdAt: string;
  createdBy: IdNameDto | null;
  image: AssetDto | null;
};

export type EmergencyContactDto = {
  name: string;
  contact: string;
  relationship: string;
};

export type ListManagerDto = {
  /**
   * @format date-time
   */
  startDate?: string;
  gender: "Male" | "Female" | "Not disclosed";
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number | null;
  id: string;
  user: ListManagerUserDto;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  emergencyContact: EmergencyContactDto | null;
};

export type ListManagerResponseDto = {
  message: string;
  data: ListManagerDto[];
  pagination: PaginationResponseDto;
};

export type ListCustomerUserDto = {
  id: string;
  customer: IdNameDto;
  user: ListManagerUserDto;
};

export type ListCustomerUserResponseDto = {
  message: string;
  data: ListCustomerUserDto[];
  pagination: PaginationResponseDto;
};

export type ListGeneralDto = {
  /**
   * @format date-time
   */
  startDate?: string;
  gender: "Male" | "Female" | "Not disclosed";
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number | null;
  id: string;
  user: ListManagerUserDto;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  emergencyContact: EmergencyContactDto | null;
};

export type ListCleanerResponseDto = {
  message: string;
  data: ListGeneralDto[];
  pagination: PaginationResponseDto;
};

export type GetGeneralDto = {
  /**
   * @format date-time
   */
  startDate?: string;
  gender: "Male" | "Female" | "Not disclosed";
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number | null;
  id: string;
  user: ListManagerUserDto;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  attachments: AssetDto[];
  emergencyContact: EmergencyContactDto | null;
};

export type GetCleanerResponseDto = {
  message: string;
  data: GetGeneralDto;
};

export type ListManagerAssignedCustomersDto = {
  id: string;
  customer: IdNameDto;
};

export type ListManagerAssignedCustomersResponseDto = {
  message: string;
  data: ListManagerAssignedCustomersDto[];
  pagination: PaginationResponseDto;
};

export type GetCustomerUserResponseDto = {
  message: string;
  data: ListCustomerUserDto;
};

export type GetManagerDto = {
  /**
   * @format date-time
   */
  startDate?: string;
  gender: "Male" | "Female" | "Not disclosed";
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number | null;
  id: string;
  user: ListManagerUserDto;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  emergencyContact: EmergencyContactDto | null;
  attachments: AssetDto[];
};

export type GetManagerResponseDto = {
  message: string;
  data: GetManagerDto;
};

export type CreateManagerDto = {
  /**
   * @format date-time
   */
  startDate?: string;
  gender: "Male" | "Female" | "Not disclosed";
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number;
  customerIds?: string[];
  /**
   * @format binary
   */
  photo?: Blob;
  attachments?: Blob[];
  fullName: string;
  email: string;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  emergencyContact?: EmergencyContactDto;
};

export type AssignCustomerToManagerRequestDto = {
  added?: string[];
  removed?: string[];
};

export type UpdateManagerDto = {
  fullName?: string;
  ended?: boolean;
  phone?: string;
  address?: string;
  /**
   * @format date-time
   */
  dateOfBirth?: string;
  /**
   * @format date-time
   */
  startDate?: string;
  gender?: "Male" | "Female" | "Not disclosed";
  employmentStatus?: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number;
  customerIds?: string[];
  /**
   * @format binary
   */
  photo?: Blob;
  emergencyContact?: EmergencyContactDto;
};

export type CreateCleanerDto = {
  employmentStatus: "Full-time" | "Part-time" | "Casual" | "Contract";
  gender: "Male" | "Female" | "Not disclosed";
  yearOfExperience?: number;
  /**
   * @format binary
   */
  photo?: Blob;
  attachments?: Blob[];
  email: string;
  fullName: string;
  phone: string;
  address: string;
  /**
   * @format date-time
   */
  dateOfBirth: string;
  /**
   * @format date-time
   */
  startDate: string;
  emergencyContact?: EmergencyContactDto;
};

export type UpdateCleanerDto = {
  fullName?: string;
  ended?: boolean;
  phone?: string;
  address?: string;
  /**
   * @format date-time
   */
  dateOfBirth?: string;
  /**
   * @format date-time
   */
  startDate?: string;
  gender?: "Male" | "Female" | "Not disclosed";
  employmentStatus?: "Full-time" | "Part-time" | "Casual" | "Contract";
  yearOfExperience?: number;
  email?: string;
  /**
   * @format binary
   */
  photo?: Blob;
  emergencyContact?: EmergencyContactDto;
};

export type CreateCustomerUserRequestDto = {
  email: string;
  salutation?: string;
  /**
   * @format binary
   */
  photo?: Blob;
  fullName: string;
  phone: string;
  customerId: string;
};

export type ListSOWDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  group: IdNameDto | null;
};

export type ListSOWResponseDto = {
  message: string;
  data: ListSOWDto[];
  pagination: PaginationResponseDto;
};

export type GetSOWResponseDto = {
  message: string;
  data: ListSOWDto;
};

export type CreateScopeOfWorkRequestDto = {
  /**
   * @format uuid
   */
  sowGroupId?: string;
  title: string;
  description: string;
};

export type UpdateScopeOfWorkRequestDto = {
  /**
   * @format uuid
   */
  sowGroupId?: string;
  title?: string;
  description?: string;
};

export type ListSOWGroupDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
};

export type ListSOWGroupResponseDto = {
  message: string;
  data: ListSOWGroupDto[];
  pagination: PaginationResponseDto;
};

export type GetSOWGroupSow = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
};

export type GetSOWGroupDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  sows: GetSOWGroupSow[];
};

export type GetSOWGroupResponseDto = {
  message: string;
  data: GetSOWGroupDto;
};

export type CreateScopeOfWorkGroupRequestDto = {
  description?: string;
  title: string;
};

export type UpdateSowGroupRequestDto = {
  description?: string;
  title?: string;
};

export type LocationDto = {
  postcode?: string | null;
  placeId?: string | null;
  latitude: number;
  address: string;
  longitude: number;
  tolerableRadius: number;
};

export type ListSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: LocationDto;
  customer: IdNameDto;
  createdBy: IdNameDto | null;
};

export type ListSiteResponseDto = {
  message: string;
  data: ListSiteDto[];
  pagination: PaginationResponseDto;
};

export type ListSiteCleanersDto = {
  id: string;
  name: string;
  /**
   * @format uuid
   */
  userId: string;
};

export type ListSiteCleanersResponseDto = {
  message: string;
  data: ListSiteCleanersDto[];
  pagination: PaginationResponseDto;
};

export type ListSiteManagersDto = {
  id: string;
  name: string;
  /**
   * @format uuid
   */
  userId: string;
};

export type ListSiteManagersResponseDto = {
  message: string;
  data: ListSiteManagersDto[];
  pagination: PaginationResponseDto;
};

export type ListSiteExternalManagersDto = {
  id: string;
  name: string;
  /**
   * @format uuid
   */
  userId: string;
};

export type ListSiteExternalManagersResponseDto = {
  message: string;
  data: ListSiteExternalManagersDto[];
  pagination: PaginationResponseDto;
};

export type GetSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: LocationDto;
  customer: IdNameDto;
  createdBy: IdNameDto | null;
};

export type GetSiteResponseDto = {
  message: string;
  data: GetSiteDto;
};

export type CreateSiteLocationDto = {
  postcode?: string;
  placeId?: string;
  tolerableRadius?: number;
  address: string;
  latitude: number;
  longitude: number;
};

export type CreateSiteRequestDto = {
  description?: string;
  title: string;
  /**
   * @format uuid
   */
  clientId: string;
  location: CreateSiteLocationDto;
};

export type GenerateQrTokenRequestDto = {
  entityType: "site" | "customer";
  /**
   * @format uuid
   */
  entityId: string;
};

export type GenerateQrTokenDto = {
  token: string;
};

export type GenerateQrTokenResponseDto = {
  message: string;
  data: GenerateQrTokenDto;
};

export type UpdateSiteCleanersDto = {
  removed?: string[];
  added?: string[];
};

export type UpdateSiteManagersDto = {
  removed?: string[];
  added?: string[];
};

export type UpdateSiteCustomerUsersDto = {
  removed?: string[];
  added?: string[];
};

export type UpdateSiteLocationDto = {
  postcode?: string;
  placeId?: string;
  tolerableRadius?: number;
  address?: string;
  latitude?: number;
  longitude?: number;
};

export type UpdateSiteRequestDto = {
  title?: string;
  description?: string;
  cleaner?: UpdateSiteCleanersDto;
  manager?: UpdateSiteManagersDto;
  customerUser?: UpdateSiteCustomerUsersDto;
  location?: UpdateSiteLocationDto;
};

export type ListJobAssignedStaffDto = {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  /**
   * @format uuid
   */
  userId: string;
};

export type GetJobSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  address: LocationDto;
  title: string;
};

export type ListJobDto = {
  status: "Scheduled" | "In Progress" | "Completed" | "Cancelled";
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  jobNumber: number;
  customer: IdNameDto | null;
  assignedStaff: ListJobAssignedStaffDto | null;
  startAt: string | null;
  createdAt: string;
  site: GetJobSiteDto | null;
};

export type ListJobResponseDto = {
  message: string;
  data: ListJobDto[];
  pagination: PaginationResponseDto;
};

export type AdminGetJobSummaryDto = {
  status: "Scheduled" | "In Progress" | "Completed" | "Cancelled";
  count: number;
};

export type AdminGetJobSummaryResponseDto = {
  message: string;
  data: AdminGetJobSummaryDto[];
};

export type UpdateChecklistSowRequestDto = {
  status?: "Pending" | "Ongoing" | "Completed" | "Cancelled";
  remarks?: string;
  attachments?: Blob[];
};

export type GetJobChecklistDto = {
  status: "Pending" | "Ongoing" | "Completed" | "Cancelled";
  remarks?: string | null;
  /**
   * @format uuid
   */
  id: string;
  name: string;
  attachments: AssetDto[];
};

export type GetJobDto = {
  remarks?: string | null;
  description?: string | null;
  status: "Scheduled" | "In Progress" | "Completed" | "Cancelled";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  jobNumber: number;
  startAt: string | null;
  createdAt: string;
  assignedStaff: IdNameDto | null;
  site: GetJobSiteDto | null;
  checklists: GetJobChecklistDto[];
  assets: AssetDto[];
};

export type GetJobResponseDto = {
  message: string;
  data: GetJobDto;
};

export type CreateJobChecklistDto = {
  remarks?: string;
  /**
   * @format uuid
   */
  sowId: string;
};

export type CreateJobRequestDto = {
  description?: string;
  /**
   * @format uuid
   */
  assignedCleanerId?: string;
  /**
   * @format uuid
   */
  jobRequestId?: string;
  assets?: Blob[];
  title: string;
  siteId: string;
  /**
   * @format date-time
   */
  startAt: string;
  checklists: CreateJobChecklistDto[];
  /**
   * @format uuid
   */
  customerId: string;
};

export type UpdateJobRequestDto = {
  title?: string;
  description?: string;
  /**
   * @format date-time
   */
  startAt?: string;
  status?: "Scheduled" | "In Progress" | "Completed" | "Cancelled";
  remarks?: string;
};

export type AdminListJobRequestsSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  location: LocationDto;
};

export type AdminListJobRequestsDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  isApproved: boolean;
  /**
   * @format date-time
   */
  startAt: string;
  site: AdminListJobRequestsSiteDto;
  requestedBy: IdNameDto;
};

export type AdminListJobRequestResponseDto = {
  message: string;
  data: AdminListJobRequestsDto[];
  pagination: PaginationResponseDto;
};

export type AdminGetJobRequestsDto = {
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  isApproved: boolean;
  /**
   * @format date-time
   */
  startAt: string;
  site: AdminListJobRequestsSiteDto;
  requestedBy: IdNameDto;
  customer: IdNameDto;
};

export type AdminGetJobRequestResponseDto = {
  message: string;
  data: AdminGetJobRequestsDto;
};

export type JobRequestDto = {
  description?: string;
  title: string;
  startAt: string;
  /**
   * @format uuid
   */
  siteId: string;
};

export type AdminGetIncidentSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  address: string;
};

export type AdminListIncidentDto = {
  description?: string | null;
  type: "Issue" | "Request" | "Seeking Information";
  priority: "Low" | "Medium" | "High";
  status: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  site: AdminGetIncidentSiteDto;
  reportedBy: IdNameDto | null;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type AdminListIncidentResponseDto = {
  message: string;
  data: AdminListIncidentDto[];
  pagination: PaginationResponseDto;
};

export type AdminGetIncidentDto = {
  description?: string | null;
  type: "Issue" | "Request" | "Seeking Information";
  priority: "Low" | "Medium" | "High";
  status: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  site: AdminGetIncidentSiteDto;
  reportedBy: IdNameDto | null;
  assets: AssetDto[];
  /**
   * @format date-time
   */
  createdAt: string;
};

export type GetIncidentResponseDto = {
  message: string;
  data: ManagerGetIncidentDto;
};

export type AdminUpdateIncidentRequestDto = {
  title?: string;
  status?: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
  type?: "Issue" | "Request" | "Seeking Information";
  priority?: "Low" | "Medium" | "High";
  description?: string | null;
};

export type Object = {};

export type ListActivityDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  type: Record<string, any>;
  description: string;
  diff: Record<string, any>[];
  user: IdNameDto | null;
  customer: IdNameDto | null;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type ListActivityResponseDto = {
  message: string;
  data: ListActivityDto[];
  pagination: PaginationResponseDto;
};

export type DashboardSummaryDto = {
  pending: number;
  completed: number;
  upcomming: number;
  cancelled: number;
};

export type DashboardSummaryResponseDto = {
  message: string;
  data: DashboardSummaryDto;
};

export type ManagerListSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: LocationDto;
  customer: IdNameDto | null;
};

export type ManagerListSiteResponseDto = {
  message: string;
  data: ManagerListSiteDto[];
  pagination: PaginationResponseDto;
};

export type ManagerListJobRequestsSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  location: LocationDto;
};

export type ManagerListJobRequestsDto = {
  description?: string | null;
  id: string;
  title: string;
  /**
   * @format date-time
   */
  startAt: string;
  site: ManagerListJobRequestsSiteDto;
};

export type ManagerListJobRequestResponseDto = {
  message: string;
  data: ManagerListJobRequestsDto[];
  pagination: PaginationResponseDto;
};

export type ManagerGetIncidentSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  address: string;
};

export type ManagerGetIncidentDto = {
  type: "Issue" | "Request" | "Seeking Information";
  priority: "Low" | "Medium" | "High";
  status: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
  /**
   * @format uuid
   */
  id: string;
  title: string;
  description: string | null;
  site: ManagerGetIncidentSiteDto;
  reportedBy: IdNameDto | null;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type ManagerListIncidentResponseDto = {
  message: string;
  data: ManagerGetIncidentDto[];
  pagination: PaginationResponseDto;
};

export type ManagerUpdateIncidentDto = {
  status?: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
};

export type StaffListSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: LocationDto;
  customer: IdNameDto | null;
};

export type StaffListSiteResponseDto = {
  message: string;
  data: StaffListSiteDto[];
  pagination: PaginationResponseDto;
};

export type StaffGetSiteDto = {
  id: string;
  title: string;
  description: string | null;
  location: LocationDto;
  customer: IdNameDto | null;
};

export type StaffGetSiteResponseDto = {
  message: string;
  data: StaffGetSiteDto;
};

export type StaffSiteLoginSiteDto = {
  id: string;
  title: string;
  location: LocationDto;
};

export type StaffSiteLoginAttendanceDto = {
  /**
   * @format date-time
   */
  clockOut?: string | null;
  id: string;
  /**
   * @format date-time
   */
  clockIn: string;
};

export type StaffSiteLoginDto = {
  isLoggedIn: boolean;
  site: StaffSiteLoginSiteDto | null;
  attendance: StaffSiteLoginAttendanceDto | null;
};

export type StaffSiteLoginResponseDto = {
  message: string;
  data: StaffSiteLoginDto;
};

export type StaffSiteLoginRequestDto = {
  token: string;
  latitude: number;
  longitude: number;
};

export type StaffSiteLogoutRequestDto = {
  token: string;
  latitude: number;
  longitude: number;
};

export type StaffGetIncidentSiteDto = {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  address: string;
};

export type StaffGetIncidentDto = {
  type: "Issue" | "Request" | "Seeking Information";
  priority: "Low" | "Medium" | "High";
  status: "Open" | "In Progress" | "Resolved" | "Closed" | "Rejected";
  description?: string | null;
  /**
   * @format uuid
   */
  id: string;
  title: string;
  reportedBy: IdNameDto | null;
  site: StaffGetIncidentSiteDto;
  /**
   * @format date-time
   */
  createdAt: string;
};

export type StaffListIncidentResponseDto = {
  message: string;
  data: StaffGetIncidentDto[];
  pagination: PaginationResponseDto;
};

export type StaffGetIncidentResponseDto = {
  message: string;
  data: StaffGetIncidentDto;
};

export type StaffCreateIncidentReportRequestDTO = {
  description?: string;
  type?: "Issue" | "Request" | "Seeking Information";
  priority?: "Low" | "Medium" | "High";
  attachments?: Blob[];
  title: string;
  /**
   * @format uuid
   */
  siteId: string;
};

export type StartJobRequestDto = {
  /**
   * @format uuid
   */
  jobId: string;
  latitude: number;
  longitude: number;
  /**
   * @format date-time
   */
  startedAt: string;
  token: string;
};

export type StaffUpdateJobStatusRequestDto = {
  status: "Cancelled" | "Completed";
};
